<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('payments', function (Blueprint $table) {
            $table->id();

            $table->string('payment_number')->unique();

            /*
             * Generic payable source.
             *
             * Examples:
             * - Order
             * - Quotation
             * - Future paid service/support module
             */
            $table->morphs('payable');

            $table->foreignId('user_id')
                ->constrained()
                ->restrictOnDelete();

            /*
             * Snapshot of the amount being paid.
             * This remains historical even if the source amount changes later.
             */
            $table->decimal('amount', 18, 2);
            $table->string('currency', 3)->default('PHP');

            /*
             * Provider = who processes the payment.
             *
             * Examples:
             * stripe
             * manual
             * crypto
             */
            $table->string('provider')->nullable();

            /*
             * Method = how the customer pays.
             *
             * Examples:
             * card
             * gcash
             * bank_transfer
             * usdt
             * btc
             */
            $table->string('method')->nullable();

            /*
             * ID/reference generated by an external provider.
             *
             * Example:
             * Stripe PaymentIntent ID
             * Crypto gateway transaction ID
             */
            $table->string('provider_payment_id')->nullable();

            /*
             * Customer/manual reference.
             *
             * Examples:
             * GCash reference number
             * Bank transaction reference
             */
            $table->string('reference_number')->nullable();

            /*
             * Manual payment proof such as uploaded receipt/screenshot.
             */
            $table->string('proof_path')->nullable();

            $table->string('status')
                ->default('pending')
                ->index();

            /*
             * Provider-specific information that does not belong
             * in the core payment schema.
             */
            $table->json('metadata')->nullable();

            $table->text('notes')->nullable();

            $table->dateTime('submitted_at')->nullable();
            $table->dateTime('verified_at')->nullable();

            /*
             * Null = automatically verified by gateway/webhook.
             * User ID = manually verified by an admin.
             */
            $table->foreignId('verified_by')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete();

            $table->timestamps();

            $table->index(['user_id', 'status']);
            $table->index(['payable_type', 'payable_id', 'status']);
            $table->index(['provider', 'provider_payment_id']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('payments');
    }
};